name: pomodoro_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  youtube_player_flutter: ^8.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
    - assets/image copy.png
    - assets/image copy 2.png
    - assets/image copy 3.png
    - assets/image copy 4.png
    - assets/image copy 5.png
    - assets/image copy 6.png
    - assets/image copy 7.png
    - assets/image copy 8.png
    - assets/image copy 9.png
    - assets/image copy 10.png
    - assets/image copy 11.png
    - assets/image copy 12.png
    - assets/image copy 13.png
    - assets/image copy 14.png
    - assets/image copy 15.png
    - assets/image copy 16.png
    - assets/image copy 17.png
    - assets/ai copy.png
    - assets/sus copy.jpg
